apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomize
generatorOptions:
  disableNameSuffixHash: true
namespace: default  
resources:
  - deployment.yaml
  - service.yaml
secretGenerator:
- name: secrets-cloudflare-credentials
  envs:
  - secrets.env  