apiVersion: v1
kind: Service
metadata:
  name: cloudflare-exporter
spec:
  selector:
    app: cloudflare-exporter
  ports:
    - protocol: TCP
      port: 8080  
      targetPort: 8080  
  type: ClusterIP
